### ISSUE TITLE
cb-event-forwarder service consistently fails to restart

### ISSUE THREAD

**Issue by vnagendra** [carbonblack/cb-event-forwarder#16]
Once `cb-event-forwarder` starts, it seems to be really hard to restart it (due to any kind of configuration changes). This output is pretty normal in our setup. Any ideas on how to force it to restart. We obviously tried `kill -15, kill -9` etc., also tried `service cb-event-forwarder stop/restart`. 

I think the `service cb-event-forwarder force-reload` is perfect for our configuration changes. But by accident if we try to restart or stop, it goes into a funky state (or so we think). The error is the same regardless of the command (user pressing control+c after a while) 

Logs below 
```
[root@93ccfd89d468 /]# service cb-event-forwarder try-restart
Restarting cb-event-forwarder: 2015-09-28 10:50:08,528: cbint.utils: INFO: parsing configuration
2015-09-28 10:50:08,529: cbint.utils: INFO: section: bridge
2015-09-28 10:50:08,529: cbint.utils: INFO:    message_processor_count: 4
2015-09-28 10:50:08,529: cbint.utils: INFO:    server_name: customer2
2015-09-28 10:50:08,529: cbint.utils: INFO:    debug: 1
2015-09-28 10:50:08,529: cbint.utils: INFO:    cbapi_server: https://localhost/
2015-09-28 10:50:08,529: cbint.utils: INFO:    cbapi_token: REDACTED
2015-09-28 10:50:08,530: cbint.utils: INFO:    cbapi_ssl_verify: False
2015-09-28 10:50:08,530: cbint.utils: INFO:    rabbit_mq_username:
2015-09-28 10:50:08,530: cbint.utils: INFO:    rabbit_mq_password:
2015-09-28 10:50:08,530: cbint.utils: INFO:    output_type: udp
2015-09-28 10:50:08,530: cbint.utils: INFO:    udpout: graylog.internal.REDACTED.com:19384
2015-09-28 10:50:08,530: cbint.utils: INFO:    events_raw_sensor: 0
2015-09-28 10:50:08,530: cbint.utils: INFO:    events_watchlist: ALL
2015-09-28 10:50:08,531: cbint.utils: INFO:    events_feed: ALL
2015-09-28 10:50:08,531: cbint.utils: INFO:    events_alert: ALL
2015-09-28 10:50:08,531: cbint.utils: INFO:    events_binary_observed: 0
2015-09-28 10:50:08,531: cbint.utils: INFO:    events_binary_upload: 0
2015-09-28 10:50:08,531: cbeventforwarder: INFO: Got a shutdown of service
2015-09-28 10:50:08,531: cbint.utils: INFO: daemon stopping...
^CTraceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/home/builduser/rpmbuild/BUILD/cb-event-forwarder-2.0/build/cb-event-forwarder/out00-PYZ.pyz/cbint.utils.daemon", line 215, in restart
  File "/home/builduser/rpmbuild/BUILD/cb-event-forwarder-2.0/build/cb-event-forwarder/out00-PYZ.pyz/cbint.utils.daemon", line 200, in stop
KeyboardInterrupt
```

**Comment by vnagendra** [comment]
tiny bit more information. The process just got into a zombie state (which is an issue). Removing the PID file and starting the process resolved the issue.
